spring:
  freemarker:
    cache: false
  profiles:
    active: local
    include: secret
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
#        format_sql: true
        #use_sql_comments: true
        globally_quoted_identifiers: true
    defer-datasource-initialization: true
    database: mysql
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
